### PR TITLE
refactor: Relocate message handler interface

### PR DESCRIPTION
**Pull request by pxrl**
The MulticallHandler contract currently imports the SpokePool contract and experienced a bytecode change after the following unrelated commit:

86593c6

This resulted in its CREATE2 deployment address changing. The MulticallHandler doesn't actually need any of the SpokePool implementation or its dependencies, and it seems like we'd like the MulticallHandler to be deployed to the same address on as many chains as possible, so factor out the interface to a separate file to insulate it from any unintended modifications.

### CODE REVIEW

**Review by bmzig — APPROVED** [review]
Could we also just do `import { AcrossMessageHandler } from "../SpokePool.sol";` in `MulticallHandler.sol`? It also makes sense to add it to another file, so I'm fine with either.

**Comment by pxrl** [comment]
> Could we also just do `import { AcrossMessageHandler } from "../SpokePool.sol";` in `MulticallHandler.sol`? It also makes sense to add it to another file, so I'm fine with either.

Good call - I hadn't thought of that. I tried it though and I can still get the resulting bytecode to change by making simple changes in `contracts/upgradeable/MultiCallerUpgradeable.sol`.

**Review by nicholaspai — APPROVED** [review]
Does this keep the MultiCallHandler create2 address the same?

**Review by james-a-morris — APPROVED** [review]
Good call +1

**Pull request merged**
